name: Deploy Laravel Exercise

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: curl, mbstring, pdo_mysql, tokenizer, xml, zip, zlib, ctype, openssl, fileinfo, bcmath

      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node.js Dependencies
        run: npm install && npm run build

      - name: Cleanup Unnecessary Files
        run: |
          rm -rf node_modules
          rm -rf storage

      - name: Compress Project
        run: tar -czf app.tgz $(ls -A)

      - name: Deploy via SSH and SCP
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SSH_PORT }}
          scp: './app.tgz => ${{ secrets.DOCUMENT_ROOT }}'
          last_ssh: |
            cd ${{ secrets.DOCUMENT_ROOT }}
            tar -xzf app.tgz
            echo "Deployment Completed Successfully"
